### ISSUE TITLE
Allow only one instance of nheko running at the same time

### ISSUE THREAD

**Issue by vanyasem** [mujx/nheko#141]
Allow only one instance of nheko running at the same time. Trying to open a second instance should result in the current instance being restored from tray instead

### System:

- Operating System: GNU/Linux

### Steps to reproduce
Try to open nheko when you already have nheko running in background
### Actual behavior
Another instance of nheko pops up
![2017-11-26-162841_866x57_scrot](https://user-images.githubusercontent.com/13350458/33240436-ee93af28-d2c6-11e7-8122-3878a1eecbde.png)
### Expected behavior
Current background instance comes to foreground

**Comment by mujx** [comment]
That's mostly an issue with the destkop environment. It shouldn't create a new instance when there is one already running (maybe tweak the config?)

**Comment by vanyasem** [comment]
you can run only 1 telegram instance for example. it doesn't make too much sense running 2 clients at the same time. VLC has that as an option in settings (allow only one instance). it should be present in some form

**Comment by simoniz0r** [comment]
I've found myself having 3 or 4 nheko's open due to the minimize to tray behavior myself.  Personally, when I tell the app to quit, I don't expect it to minimize to tray (especially when the setting says *minimize* to tray) lol.

**Comment by jansol** [comment]
@vanyasem counterpoint: people can (and do!) have multiple matrix accounts. On telegram, whatsapp etc that is much less likely since they are tied to phone numbers. There is actually a feature request to allow multiple instances of riot for precisely this reason.

If/once there is support for signing into multiple accounts at the same time, disallowing multiple nheko instances would make a lot more sense. It could perhaps be implemented as a setting already (and maybe even default to only one instance)

**Comment by ptman** [comment]
I think it would make sense to only allow one instance per config. If nheko can be pointed to another config, then another instance should be allowed, but only one per config.

**Comment by alphapapa** [comment]
This would indeed be helpful.  I'm running the `nheko` executable I build with krunner, and there is no detection of multiple instances.

**Comment by alphapapa** [comment]
@mujx Thank you!
